### ISSUE TITLE
I Have Found Bug?????

### ISSUE THREAD

**Issue by IvarWithoutBones** [simontime/DVDLogo#1]
Teh logo neve rhit the cornor

**Comment by R2D221** [comment]
Does it, tho? I would like a formal proof on this.

**Comment by IvarWithoutBones** [comment]
I Have Wait 2 HOUR COrnor Not Hit

**Comment by sn8to** [comment]
not bug; very intended coding in order to make you mad
/s

not every dvd screensaver has the same dvd logo size and same canvas/screen size, so depending on that it would take much longer or much shorter of a time

**Comment by R2D221** [comment]
I say we close this bug.

The logo explicitly starts in a corner (https://github.com/simontime/DVDLogo/blob/master/source/main.c#L6):

    u32 xpos = 0, ypos = 0, speed = 1, col = RANDOM;

And according to [this analysis](http://lostmathlessons.blogspot.com/2016/03/bouncing-dvd-logo.html), the logo is guaranteed to hit a corner eventually (we just have to calculate how long the cycle is).

**Comment by IvarWithoutBones** [comment]
fcuk u

**Comment by simontime** [comment]
pee pee poo poo stinky #wontfix
